apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend-deployment
spec:
 selector:
   matchLabels:
    type: web
    app: fronted
 replicas: 2
 template:
   metadata:
     labels:
       type: web
       app: frontend
   spec:
    containers:
    - name: container
      image: lllth94/frontend:latest
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m