apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend-deployment
 labels:
  type: web
  app: frontend
  version: v11
spec:
 selector:
   matchLabels:
    type: web
    app: frontend
    labels: v11
 replicas: 1
 template:
   metadata:
     labels:
      type: web
      app: frontend
      version: v11
   spec:
    containers:
    - name: frontend
      image: lllth94/frontend:latest
      envFrom:
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m
